---
stateMachine:
  name: netsuite-customer-ar-tr-restlet-state-machine-${self:provider.stage}
  events:
    - schedule:
        rate: cron(0 3 * * ? *) # CST:- 10:00 PM IST:- 08:30 am
  definition:
    Comment: "State machine to update netsuit customer AR TR Restlet internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-customer-ar-tr-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: InvokeLambda
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
          - Variable: $.hasMoreData
            StringEquals: "running"
            Next: SuccessState
      InvokeLambda:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-ar-tr-${self:provider.stage}"
        Next: SecondEndChoice
      SecondEndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: InvokeLambda
      SuccessState:
        Type: Succeed