service: omni-netsuite-restlet

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: true
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 30
  memorySize: 256
  deploymentBucket: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
  role: ${ssm:/omni-dw/${self:provider.stage}/lambda/role}
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  stackTags:
    Application: OmniNetsuite
    CreateBy: BizCloudExperts
    Version: "1.0"
    Environment: ${self:provider.stage}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    DBNAME: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    USER: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    HOST: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    PASS: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    PORT: ${ssm:/omni-dw/${self:provider.stage}/db/port}
    db_username: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/name~true}
    db_host: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/port~true}
    DATABASE_NAME: ${ssm:/omni-dw/${self:provider.stage}/databaseName}
    NETSUIT_BASE_URL: ${ssm:/omni-dw/${self:provider.stage}/netsuite/baseUrl}
    NETSUIT_AR_API_ENDPOINT: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/apiEndpoint}
    NETSUIT_AR_ACCOUNT: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/account}
    NETSUIT_AR_CONSUMER_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/consumerKey}
    NETSUIT_AR_CONSUMER_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/consumerSecret}
    NETSUIT_AR_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKey}
    NETSUIT_AR_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecret}
    NETSUIT_CW_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKeyCW}
    NETSUIT_CW_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecretCW}
    NETSUIT_M1_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKeyM1}
    NETSUIT_M1_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecretM1}
    NETSUIT_TR_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKeyTR}
    NETSUIT_TR_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecretTR}
    NETSUIT_MCL_CONSUMER_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/consumerKey~true}
    NETSUIT_MCL_CONSUMER_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/consumerSecret~true}
    NETSUIT_MCL_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/tokenKeyMCL~true}
    NETSUIT_MCL_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/tokenSecretMCL~true}

    NETSUIT_AR_WDSLPATH: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/wdslPath} 
    NETSUIT_AR_ERROR_TABLE: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/dynamo/errorTable}
    NETSUIT_AR_ERROR_EMAIL_HOST: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/host}
    NETSUIT_AR_ERROR_EMAIL_USER: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/user}
    NETSUIT_AR_ERROR_EMAIL_PASS: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/pass}
    NETSUIT_AR_ERROR_EMAIL_FROM: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/from}
    NETSUIT_AR_ERROR_EMAIL_TO: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/to}
    NS_RESTLET_INVOICE_REPORT: ${self:service}-invoice-report-${self:provider.stage}
    NS_BASE_URL: ${ssm:/${self:service}/${self:provider.stage}/netsuiteBaseUrl}

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-step-functions
  - serverless-pseudo-parameters

package:
  individually: true
  exclude:
    - "node_modules/**"
    - Jenkinsfile
    - "config/**"
    - "Helpers/**"
    - "src/**"
    - "*.*"

layers:
  commonNetsuiteLibs:
    path: lambdaLayer/lib
    compatibleRuntimes:
      # - nodejs18.x
      - nodejs12.x

functions:
  #CW lambda functions
  netsuite-ar-cw-restlet: ${file(config/functions/CW/netsuite-ar-cw.yml):function}
  netsuite-customer-ar-cw-restlet: ${file(config/functions/CW/netsuite-customer-ar-cw.yml):function}
  netsuite-ap-cw-restlet: ${file(config/functions/CW/netsuite-ap-cw.yml):function}
  netsuite-vendor-ap-cw-restlet: ${file(config/functions/CW/netsuite-vendor-ap-cw.yml):function}
  #TR lambda functions
  netsuite-ar-tr-restlet: ${file(config/functions/TR/netsuite-ar-tr.yml):function}
  netsuite-customer-ar-tr-restlet: ${file(config/functions/TR/netsuite-customer-ar-tr.yml):function}
  netsuite-ap-tr-restlet: ${file(config/functions/TR/netsuite-ap-tr.yml):function}
  netsuite-vendor-ap-tr-restlet: ${file(config/functions/TR/netsuite-vendor-ap-tr.yml):function}
  #LL lambda functions
  netsuite-ar-ll-restlet: ${file(config/functions/LL/netsuite-ar-ll.yml):function}
  netsuite-customer-ar-ll-restlet: ${file(config/functions/LL/netsuite-customer-ar-ll.yml):function}
 
  #report fn
  invoice-report: ${file(config/functions/invoice-report.yml):function}

  #Intercompany fn
  netsuite-cw-intercompany-restlet: ${file(config/functions/netsuite-intercompany.yml):function}
  netsuite-tr-intercompany-restlet: ${file(config/functions/netsuite-tr-intercompany.yml):function}


stepFunctions:
  stateMachines:
    #CW Step Functions
    netsuite-customer-ar-cw-restlet: ${file(config/step-functions/CW/netsuite-customer-ar-cw-state-machine.yml):stateMachine}
    netsuite-vendor-ap-cw-restlet: ${file(config/step-functions/CW/netsuite-vendor-ap-cw-state-machine.yml):stateMachine}
    #TR Step Functions
    netsuite-customer-ar-tr-restlet: ${file(config/step-functions/TR/netsuite-customer-ar-tr-state-machine.yml):stateMachine}
    netsuite-vendor-ap-tr-restlet: ${file(config/step-functions/TR/netsuite-vendor-ap-tr-state-machine.yml):stateMachine}
    #LL Step Functions
    netsuite-customer-ar-ll-restlet: ${file(config/step-functions/LL/netsuite-customer-ar-ll-state-machine.yml):stateMachine}

    #cw intercompny 
    netsuite-cw-intercompany-restlet: ${file(config/step-functions/netsuite-intercompany-state-machine.yml):stateMachine}
    netsuite-tr-intercompany-restlet: ${file(config/step-functions/netsuite-intercompany-tr-state-machine.yml):stateMachine}