---
function:
  handler: src/M1/netsuite_ar_m1.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-ar-m1-${self:provider.stage}
  description: M1 Restlet Netsuite AR api service - ${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900
  tags:
    Name: ar-m1  
  package:
    include:
      - src/M1/netsuite_ar_m1.js
      - Helpers/**
  environment:
    NETSUITE_VENDOR_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:netsuite-vendor-ap-m1-restlet-state-machine-${self:provider.stage}
    NETSUIT_RESTLET_INV_URL: ${ssm:/omni-dw/${self:provider.stage}/invoice/apiEndpoint}
    NETSUIT_RESTLET_CM_URL: ${ssm:/omni-dw/${self:provider.stage}/creditmemo/apiEndpoint}
    FUNCTION_NAME: ${self:service}-ar-m1-${self:provider.stage}