---
stateMachine:
  name: netsuite-customer-ar-ll-restlet-state-machine-${self:provider.stage}
  events:
    - schedule:
        rate: cron(0 0 * * ? *) # UTC:- 12:00 AM CST:- 06:00 PM IST:- 05:30 AM
  definition:
    Comment: "State machine to update netsuit customer AR LL Restlet internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-customer-ar-ll-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: InvokeLambda
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
          - Variable: $.hasMoreData
            StringEquals: "running"
            Next: SuccessState
      InvokeLambda:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-ar-ll-${self:provider.stage}"
        Next: SecondEndChoice
      SecondEndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: InvokeLambda
      SuccessState:
        Type: Succeed