---
function:
  handler: src/LL/netsuite_ap_ll.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-ap-ll-${self:provider.stage}
  description: LL Restlet Netsuite AP api service - ${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/LL/netsuite_ap_ll.js
      - Helpers/**
  environment:
    NETSUITE_INTERCOMPANY_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-intercompany-ll-state-machine-${self:provider.stage}
    NETSUIT_RESTLET_VB_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorbill/apiEndpoint}
    NETSUIT_RESTLET_VC_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorcredit/apiEndpoint}
    FUNCTION_NAME: ${self:service}-ap-ll-${self:provider.stage}
    NS_BILL_PAYMENT_URL: ${ssm:/${self:service}/${self:provider.stage}/netsuiteBillPaymentUrl}