---
stateMachine:
  name: netsuite-cross-dock-wt-state-machine-${self:provider.stage}
  # events:
  #   - schedule:
  #       # rate: cron(0 7 * * ? *) #  UTC:- 7:00 AM / 2:00 am CST
  #       rate: cron(30 9 * * ? *) #  UTC:- 9:300 AM / 3:00 pm CST
  definition:
    Comment: "State machine to update netsuite cross dock wt invoices"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:netsuite-cross-dock-wt-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed
