---
function:
  handler: src/AGW/netsuite_ar_agw.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-ar-agw-${self:provider.stage}
  description: AGW Restlet Netsuite AR api service - ${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900
  tags:
    Name: ar-agw
  package:
    include:
      - src/AGW/netsuite_ar_agw.js
      - Helpers/**
  environment:
    NETSUITE_VENDOR_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:netsuite-vendor-ap-agw-restlet-state-machine-${self:provider.stage}
    NETSUIT_RESTLET_INV_URL: ${ssm:/omni-dw/${self:provider.stage}/invoice/apiEndpoint}
    NETSUIT_RESTLET_CM_URL: ${ssm:/omni-dw/${self:provider.stage}/creditmemo/apiEndpoint}
