---
function:
  handler: src/AGW/netsuite_customer_ar_agw.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-customer-ar-agw-${self:provider.stage}
  description: AGW Restlet Netsuite customer AR api service - ${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/AGW/netsuite_customer_ar_agw.js
      - Helpers/**
  environment:
    NETSUITE_AR_AGW_CUSTOMER_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:netsuite-customer-ar-agw-restlet-state-machine-${self:provider.stage}
