---
function:
  handler: src/TR/netsuite_ar_tr.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-ar-tr-${self:provider.stage}
  description: TR Restlet Netsuite AR api service - ${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/TR/netsuite_ar_tr.js
      - Helpers/**
  environment:
    NETSUITE_VENDOR_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:netsuite-vendor-ap-tr-restlet-state-machine-${self:provider.stage}
    NETSUIT_RESTLET_INV_URL: ${ssm:/omni-dw/${self:provider.stage}/invoice/apiEndpointSb2}
    NETSUIT_RESTLET_CM_URL: ${ssm:/omni-dw/${self:provider.stage}/creditmemo/apiEndpointSb2}
