---
function:
  handler: src/TR/netsuite_ap_tr.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-ap-tr-${self:provider.stage}
  description: TR Restlet Netsuite AP api service - ${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/TR/netsuite_ap_tr.js
      - Helpers/**
  environment:
    NETSUITE_INTERCOMPANY_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-intercompany-tr-state-machine-${self:provider.stage}
    NETSUIT_RESTLET_VB_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorbill/apiEndpointSb2}
    NETSUIT_RESTLET_VC_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorcredit/apiEndpointSb2}
