---
stateMachine:
  name: netsuite-customer-ar-m1-restlet-state-machine-${self:provider.stage}
  # events:
  #   - schedule:
  #       rate: cron(0 15 * * ? *) # CST:- 10:00 AM IST:- 08:30 pm
  definition:
    Comment: "State machine to update netsuit customer AR M1 Restlet internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-customer-ar-m1-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: InvokeLambda
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      InvokeLambda:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-ar-m1-${self:provider.stage}"
        Next: SecondEndChoice
      SecondEndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: InvokeLambda
      SuccessState:
        Type: Succeed