---
stateMachine:
  name: netsuite-customer-ar-agw-restlet-state-machine-${self:provider.stage}
  # events:
  #   - schedule:
  #       rate: cron(30 15 * * ? *) # 3:30 PM UTC, CST: 9:30 AM, IST: 8:00 PM
  #   - schedule:
  #       rate: cron(30 18 * * ? *) # 6:30 PM UTC, CST: 12:30 PM, IST: 11:00 PM
  #   - schedule:
  #       rate: cron(30 21 * * ? *) # 9:30 PM UTC, CST: 3:30 PM, IST: 1:00 AM
  definition:
    Comment: "State machine to update netsuit customer AR CW Restlet internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-customer-ar-agw-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: InvokeLambda
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
          - Variable: $.hasMoreData
            StringEquals: "running"
            Next: SuccessState
      InvokeLambda:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-ar-agw-${self:provider.stage}"
        Next: SecondEndChoice
      SecondEndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: InvokeLambda
      SuccessState:
        Type: Succeed
