---
function:
  handler: src/CW/netsuite_customer_ar_cw.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-customer-ar-cw-${self:provider.stage}
  description: CW Restlet Netsuite customer AR api service - ${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 900
  tags:
    Name: customer-ar-cw 
  package:
    include:
      - src/CW/netsuite_customer_ar_cw.js
      - Helpers/**
  environment:
    NETSUITE_AR_CW_CUSTOMER_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:netsuite-customer-ar-cw-restlet-state-machine-${self:provider.stage}
