---
stateMachine:
  name: netsuite-customer-ar-cw-restlet-state-machine-${self:provider.stage}
  # events:
  #   - schedule:
  #       rate: cron(0 15 * * ? *) # CST:- 10:00 AM IST:- 08:30 pm
  #   - schedule:
  #       rate: cron(0 18 * * ? *) # CST:- 01:00 PM IST:- 11:30 pm
  #   - schedule:
  #       rate: cron(0 20 * * ? *) # CST:- 03:00 PM IST:- 01:30 am
  definition:
    Comment: "State machine to update netsuit customer AR CW Restlet internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-customer-ar-cw-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: InvokeLambda
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
          - Variable: $.hasMoreData
            StringEquals: "running"
            Next: SuccessState
      InvokeLambda:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-ar-cw-${self:provider.stage}"
        Next: SecondEndChoice
      SecondEndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: InvokeLambda
      SuccessState:
        Type: Succeed
